[theme]
base="dark"
primaryColor="#258cf4"
backgroundColor="#0F172A"
secondaryBackgroundColor="#1E293B"
textColor="#ffffff"
font="sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
